# Generated by Django 2.1.2 on 2018-11-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='username',
            field=models.CharField(default='A0', max_length=30),
        ),
    ]
