# Generated by Django 2.1.2 on 2018-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_decision_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='question',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='decision',
            name='username',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
