# Generated by Django 2.1.2 on 2018-12-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0003_auto_20181113_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='option_3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='decision',
            name='option_4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='decision',
            name='option_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='decision',
            name='option_2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
