# Generated by Django 2.1.4 on 2019-01-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=50)),
                ('restaurant_city', models.CharField(max_length=50)),
                ('restaurant_type', models.CharField(max_length=50)),
                ('what_we_ate', models.CharField(max_length=250)),
                ('when_we_are', models.DateTimeField()),
                ('rating_michael', models.IntegerField()),
                ('rating_coly', models.IntegerField()),
                ('would_come_again', models.IntegerField()),
            ],
        ),
    ]
