# Generated by Django 2.1.4 on 2019-01-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='meal_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rating_coly',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'It was ok'), (4, 'Good'), (5, 'Amazing')], default=3),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rating_michael',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Not good'), (3, 'It was ok'), (4, 'Good'), (5, 'Amazing')], default=3),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='would_come_again',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
