# Generated by Django 2.1.4 on 2019-01-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20190106_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='when_we_are',
            new_name='when_we_ate',
        ),
    ]
